import 'package:flutter/material.dart';
import 'package:flutterapp/plantapp/generatedgrootwidget/generated/Generated2nd_phoneWidget.dart';

/* Frame Groot
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGrootWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 918.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: MediaQuery.of(context).size.width*.80,
                      height: 844.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          clipBehavior: Clip.none,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 30, 30, 30),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 391.0,
                              height: 918.0,
                              child: Generated2nd_phoneWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
